name: Deploy to Production (EB)

on:
  push:
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: '18' }
      - run: npm ci
      - name: Zip for EB
        run: zip -r my-node-app.zip .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name my-node-app \
            --version-label ${{ github.ref_name }} \
            --source-bundle S3Bucket=${{ secrets.EB_S3_BUCKET }},S3Key=my-node-app-${{ github.ref_name }}.zip
          aws elasticbeanstalk update-environment \
            --environment-name my-node-app-prod \
            --version-label ${{ github.ref_name }}

